oa3_spec: apps/app-backend/api/internal.yaml
name: opex_api_service_app_backend
location: Italy North
timespan: 5m
evaluation_frequency: 10
evaluation_time_window: 20
event_occurrences: 1
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-itn-common-rg-01/providers/Microsoft.Network/applicationGateways/io-p-itn-agw-01
action_groups:
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-itn-svc-rg-01/providers/Microsoft.Insights/actiongroups/io-p-svc-offcall-ag-01
overrides:
  hosts:
    - app-backend.io.italia.it
    - api-app.io.pagopa.it
