name: Opex Dashboard OpenAPI App Backend Catalog Internal

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/app-backend/api/external.yaml'
      - '.github/workflows/opex_api_app_backend_external.yml'
      - '.opex/api_app_backend_external/**'

env:
  API_NAME: api_app_backend_external
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  DOCKER_IMAGE_TAG: sha256:eb3354b7e5c07e9557182828489fc0bf8092dd80886035429268d019250f5cd3

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: opex-prod-cd
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}

    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # from https://github.com/pagopa/opex-dashboard-azure-action/
      - uses: pagopa/opex-dashboard-azure-action@3ad80a5e4a2d5a8f342615637072f21b687320ce # action v1.2.1
        with:
          environment: prod
          api-name: ${{ env.API_NAME }}
          config: .opex/${{ env.API_NAME }}/env/prod/config.yaml
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          # from https://github.com/pagopa/opex-dashboard-azure-action/pkgs/container/opex-dashboard-azure-action
          docker-version: ${{ env.DOCKER_IMAGE_TAG }}
